change to prepend
rhysawilliams2010/giphy-search pull request #1
Opened 2020-08-26 00:48 UTC by korbzilla

changed from append to prepend so we can see latest results

2020-09-01 23:53 UTC, sudboy123 commented
why

2020-09-01 23:54 UTC, chromemaster4756 requested changes

2020-09-01 23:54 UTC, chromemaster4756 commented on index.html
> +            <iframe src="${o.embed_url}" width="" height="429" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
Please don't delete the width attribute.

2020-09-01 23:54 UTC, sudboy123 commented
korben

2020-09-01 23:55 UTC, chromemaster4756 commented
yeet

2020-09-01 23:57 UTC, chromemaster4756 approved these changes

2020-09-01 23:58 UTC, merged

2020-09-01 23:58 UTC, chromemaster4756 commented
*claps* meme *claps* review

2020-09-02 00:23 UTC, sudboy123 commented
where? why?

2020-09-02 00:25 UTC, chromemaster4756 commented
yep